### ISSUE TITLE
IRC web service

### ISSUE THREAD

**Issue by elifoster** [CurseStaff/OreDict#12]
Could an IRC web service be added with the following settings:

Server: irc.esper.net
Port: 6667
Room: #FTB-Wiki-Dev
Nick: OreDict
Branches:
NickServ Password:
SSL: false
Message Without Join: true
No colors: false
Long URL: false
Notice: true

**Comment by Alexia** [comment]
What will the purpose of the IRC hook be?  For OreDict to broadcast messages to the room or something else?

**Comment by elifoster** [comment]
Changes made to the repo will be sent in the room. Also, my mistake, it's actually a service. I'll update CurseStaff/Tilesheets#13 as well

**Comment by Alexia** [comment]
I added the service!  Lets see if it notifies for this message.

**Comment by elifoster** [comment]
Oh no, I believe it only notifies the channel about commits. I could be wrong, but that's all I've seen so far. I could probably add some support to [LittleHelper](https://github.com/elifoster/satanicbot) for other types of changes to GitHub repos, but it'd probably take a very long time.

**Comment by Alexia** [comment]
I created a README to test it and it works.

[17:13] -OreDict-	[OreDict] Alexia pushed 1 new commit to master: http://git.io/v0dfb
[17:13] -OreDict-	OreDict/master 2d91a71 Alexia E. Smith: Create README.md
