### ISSUE TITLE
Naming consistency

### ISSUE THREAD

**Issue by satanicsanta** [CurseStaff/OreDict#5]
It's called "Ore Dict" as well as "OreDict" in many places. We should decide on a single term. Personally, I prefer "OreDict" because it's closer to what people call the Minecraft oreDictionary.

**Comment by Telshin** [comment]
I'm okay with this. I'll get everything changed over in the extension to OreDict.

**Comment by Telshin** [comment]
Let me know if you find any other changes you would like to the naming after 345046566e54e820208469e0ad244e595ef8b369 commit.

**Comment by satanicsanta** [comment]
Telshin pls merge
